name: Musical Sniffle CI / CD

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  release:
    types:
      - created
jobs:
  ci-develop:
    runs-on: [ubuntu-20.04]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin develop
      - run: npm i --force
      - run: npm run affected:lint -- --base=remotes/origin/develop --head=HEAD --parallel
      - run: npm run affected:test -- --base=remotes/origin/develop --head=HEAD --parallel
      - run: npm run affected:build -- --base=remotes/origin/develop --head=HEAD --parallel
        env:
          CI: true
